### Placeholder YAML metainformation description ###
# Brygg Ullmer, Clemson University, 2021-12-16

urlBase:  #initially, in github
authors:  #initally, email specified
GCDs:     #greatest common denominators

### end ###

